"use client";

import { useEffect, useState } from "react";

interface EvalResults {
  runId?: string;
  timestamp?: string;
  aggregate?: unknown;
  methodology?: unknown;
  tasks?: unknown[];
}

export default function WhyWebMCP() {
  const [evals, setEvals] = useState<EvalResults | null>(null);
  const [missing, setMissing] = useState(false);

  useEffect(() => {
    let cancelled = false;
    fetch("/eval-results.json")
      .then((response) =>
        response.ok ? response.json() : Promise.reject(new Error("missing"))
      )
      .then((json: EvalResults) => {
        if (!cancelled) setEvals(json);
      })
      .catch(() => {
        if (!cancelled) setMissing(true);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <section className="panel" aria-label="Why WebMCP">
      <h2>Why WebMCP, not browser actuation?</h2>
      <div className="grid">
        <div>
          <p className="group-label">Ordinary actuation</p>
          <p className="muted">
            The agent must infer: what this control means, which
            accessibility adaptations exist, how to modify them safely, and
            whether the change worked. Its only remediation strategy is
            arbitrary DOM injection, and it has no declared verification.
          </p>
        </div>
        <div>
          <p className="group-label">WebMCP (A11yMCP)</p>
          <p className="muted">
            The website declares: capabilities, schemas, supported
            remediation, live state, and verification. The agent discovers,
            negotiates, applies scoped changes with approval, and verifies
            against the site's own contract.
          </p>
        </div>
      </div>

      <p className="group-label">Measured comparison</p>
      {evals ? (
        <pre className="code">{JSON.stringify(evals.aggregate, null, 2)}</pre>
      ) : missing ? (
        <p className="muted">
          Measured benchmark pending. It is generated by the evaluation
          harness (npm run eval:webmcp); numbers are produced by real runs
          and are never entered manually.
        </p>
      ) : (
        <p className="muted">Loading evaluation results…</p>
      )}

      {evals?.methodology ? (
        <>
          <p className="group-label">Methodology</p>
          <pre className="code">
            {JSON.stringify(evals.methodology, null, 2)}
          </pre>
        </>
      ) : null}
    </section>
  );
}